# -*- coding: utf-8 -*-
"""Data Modelling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E8BZmw_eXVXE25C-WCOzhmuU7q88W4fE

# **EDA ANALYSIS**
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# pip install tensorflow --quiet

df = pd.read_csv(r"C:\Users\Suva\Documents\MSC_DS_AI\ML\Project\final_data_output_new.csv")

"""**BASIC INFO**"""

# Basic info
print(df.info())
print(df.isnull().sum())

"""**SENTIMENT DISTRIBUTION**"""

sns.countplot(x="sentiment", data=df)
plt.title("Sentiment Distribution")
plt.show()

"""**REVIEW LENGTH DISTRIBUTION**"""

df['review_length'] = df['opinion'].apply(lambda x: len(x.split()))
sns.histplot(df['review_length'], bins=30, kde=True)
plt.title("Review Length Distribution")
plt.show()

"""**ASPECT VS SENTIMENT**"""

sns.countplot(x="primary_aspect", hue="sentiment", data=df)
plt.title("Aspect-wise Sentiment")
plt.xticks(rotation=90)   # rotate labels vertically
plt.show()

"""**UNDERSAMPLING**"""

from sklearn.utils import resample

# Separate classes
neutral = df[df.sentiment=="neutral"]
positive = df[df.sentiment=="positive"]
negative = df[df.sentiment=="negative"]

# Downsample neutral to match positive
neutral_downsampled = resample(neutral,
                               replace=False,
                               n_samples=len(negative),
                               random_state=42)

# Downsample positive to match negative
positive_downsampled = resample(positive,
                               replace=False,
                               n_samples=len(negative),
                               random_state=42)

# Combine back
df_balanced = pd.concat([neutral_downsampled, positive_downsampled, negative])

"""**SENTIMENT DISTRIBUTION for DOWNSAMPLED DATA**"""

sns.countplot(x="sentiment", data=df_balanced)
plt.title("Sentiment Distribution")
plt.show()







"""# **DATA PREPROCESSING**"""

# pip install pandas scikit-learn imbalanced-learn nltk --quiet

import nltk
from nltk.corpus import movie_reviews
from nltk.tokenize import sent_tokenize, word_tokenize
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer, WordNetLemmatizer
from nltk import pos_tag, ne_chunk
from collections import Counter

# """**CATEGORIES & COUNT**"""

categories = df_balanced["sentiment"].unique()

print("\nCategories:", categories)
print("Documents per category:")
for cat in categories:
    count = (df_balanced["sentiment"] == cat).sum()
    print(f"{cat}: {count}")

"""**LOWERCASING**"""

df_balanced["lowercase_text"] = df_balanced["opinion"].astype(str).str.lower()
# Show first few rows
print(df_balanced[["opinion", "lowercase_text"]].head())

"""**TOKENIZATION**"""

df_balanced["sentences"] = df_balanced["lowercase_text"].astype(str).apply(lambda x: sent_tokenize(x))
df_balanced["words"] = df_balanced["lowercase_text"].astype(str).apply(lambda x: word_tokenize(x))
df_balanced["num_sentences"] = df_balanced["sentences"].apply(len)

# Show a few examples
for i, row in df_balanced.head().iterrows():
    print(f"\nReview {i+1}:")
    print("Number of sentences:", row["num_sentences"])
    print("First sentence:", row["sentences"][:1])
    print("First 10 words:", row["words"][:10])

"""**REMOVING STOPWORDS**"""

NEGATIONS = {"no","not","nor","never","n't"}
stop_words = set(stopwords.words("english")) - NEGATIONS

df_balanced["alpha_tokens"] = df_balanced["words"].apply(
    lambda toks: [t for t in toks if (t in NEGATIONS) or (t.isalpha() and t not in stop_words)]
)

print(df_balanced[["alpha_tokens"]].head())

"""**LEMMATIZE**"""

lemmatizer = WordNetLemmatizer()
df_balanced["lemmatized_words"] = df_balanced["alpha_tokens"].apply(
    lambda ws: [lemmatizer.lemmatize(w, pos="v") for w in ws]
)
print(df_balanced[["lemmatized_words"]].head())

"""**FINAL TEXT FOR VECTORIZER**"""

df_balanced["clean_text"] = df_balanced["lemmatized_words"].apply(lambda ws: " ".join(ws))

print(df_balanced[["clean_text"]].head())







"""# **TRAIN LINEAR SVM, RANDOM FOREST, SIMPLE NEURAL NETWORK MODELS AND COMPARE THOSE SELECT THE BEST ONE**"""

import pandas as pd
import numpy as np
import joblib
import pickle
import warnings
warnings.filterwarnings("ignore")

# --- 0) Data (assumes df_balanced with df_balanced['clean_text'] and df_balanced['sentiment']) ---
assert "clean_text" in df_balanced.columns, "clean_text column not found."
assert "sentiment" in df_balanced.columns, "sentiment column not found."

TEXT_COL = "clean_text"
TARGET_COL = "sentiment"

X_all = df_balanced[TEXT_COL].astype(str).values
y_all = df_balanced[TARGET_COL].astype(str).values

"""**TRAIN TEST SPLIT**"""

from sklearn.model_selection import train_test_split
X_train_text, X_test_text, y_train, y_test = train_test_split(
    X_all, y_all, test_size=0.2, random_state=42, stratify=y_all
)

"""**TF-IDF**"""

from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer(
    ngram_range=(1,2),    # helps with "not good", etc.
    min_df=2,
    max_df=0.95,
    strip_accents="unicode",
    lowercase=True,
    max_features=30000     # adjust based on RAM
)
X_train = tfidf.fit_transform(X_train_text)
X_test  = tfidf.transform(X_test_text)

"""**ENCODERS / CLASS WEIGHTS FOR NN**"""

from sklearn.preprocessing import LabelEncoder
from sklearn.utils.class_weight import compute_class_weight
le = LabelEncoder()
y_train_enc = le.fit_transform(y_train)
y_test_enc  = le.transform(y_test)
classes = np.unique(y_train_enc)
class_weights = compute_class_weight(class_weight="balanced", classes=classes, y=y_train_enc)
class_weight_dict = {int(c): w for c, w in zip(classes, class_weights)}

"""**METRICS HELPER**"""

from sklearn.metrics import accuracy_score, f1_score, classification_report, confusion_matrix

def evaluate_model(name, y_true, y_pred, labels):
    acc = accuracy_score(y_true, y_pred)
    f1_macro = f1_score(y_true, y_pred, average="macro")
    f1_per_class = f1_score(y_true, y_pred, average=None)
    print(f"\n=== {name} ===")
    print(f"Accuracy: {acc:.4f} | Macro-F1: {f1_macro:.4f}")
    print("Per-class F1 (label order):", labels)
    print(np.round(f1_per_class, 4))
    print("\nClassification Report:\n", classification_report(y_true, y_pred, target_names=le.classes_))
    print("Confusion Matrix:\n", confusion_matrix(y_true, y_pred))
    return {"model": name, "accuracy": acc, "f1_macro": f1_macro}

results = []

"""**LINEAR SVM MODEL**"""

from sklearn.svm import LinearSVC
svm_clf = LinearSVC(class_weight="balanced", C=1.0, random_state=42)
svm_clf.fit(X_train, y_train)
svm_pred = svm_clf.predict(X_test)
results.append(evaluate_model("Linear SVM", y_test, svm_pred, le.classes_))

"""**RANDOM FOREST MODEL**"""

from sklearn.ensemble import RandomForestClassifier
rf_clf = RandomForestClassifier(
    n_estimators=300,
    max_depth=None,
    n_jobs=-1,
    random_state=42,
    class_weight="balanced_subsample"
)
rf_clf.fit(X_train, y_train)
rf_pred = rf_clf.predict(X_test)
results.append(evaluate_model("Random Forest", y_test, rf_pred, le.classes_))

"""**SIMPLE NEURAL NETWORK**"""

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

# Convert sparse to dense (may be heavy; watch memory)
X_train_dense = X_train.toarray().astype("float32")
X_test_dense  = X_test.toarray().astype("float32")

num_features = X_train_dense.shape[1]
num_classes = len(le.classes_)

nn = keras.Sequential([
    layers.Input(shape=(num_features,)),
    layers.Dense(256, activation="relu"),
    layers.Dropout(0.3),
    layers.Dense(128, activation="relu"),
    layers.Dropout(0.3),
    layers.Dense(num_classes, activation="softmax")
])

nn.compile(
    optimizer=keras.optimizers.Adam(learning_rate=1e-3),
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

early_stop = keras.callbacks.EarlyStopping(
    monitor="val_loss", patience=3, restore_best_weights=True
)

history = nn.fit(
    X_train_dense, y_train_enc,
    validation_split=0.1,
    epochs=15,
    batch_size=256,
    callbacks=[early_stop],
    class_weight=class_weight_dict,
    verbose=1
)

nn_pred_enc = nn.predict(X_test_dense, verbose=0).argmax(axis=1)
# map back to original string labels for consistent reporting
nn_pred = le.inverse_transform(nn_pred_enc)
results.append(evaluate_model("Simple NN (Dense TF-IDF)", y_test, nn_pred, le.classes_))

"""**COMPARE & SELECT BEST**"""

res_df = pd.DataFrame(results).sort_values("f1_macro", ascending=False).reset_index(drop=True)
print("\n=== Model Comparison (sorted by Macro-F1) ===")
print(res_df)

best_name = res_df.loc[0, "model"]
print(f"\nBest model by Macro-F1: {best_name}")

# pick the trained object
trained_models = {
    "Linear SVM": svm_clf,
    "Random Forest": rf_clf,
    "Simple NN (Dense TF-IDF)": nn
}
best_model = trained_models[best_name]

"""**SAVE MODEL & TD-IDF, ENCODER**"""

# Save the TF-IDF (shared) and the encoder for consistent inference
joblib.dump(tfidf, "tfidf_vectorizer.joblib")
joblib.dump(le, "label_encoder.joblib")

# Save best model in both formats
if best_name == "Simple NN (Dense TF-IDF)":
    # Keras saving
    nn.save("best_model_keras.h5")
    print("Saved Keras model to best_model_keras.h5")
    # also dump a lightweight wrapper for convenience
    with open("best_model_name.txt", "w") as f:
        f.write(best_name)
else:
    # scikit-learn model
    joblib.dump(best_model, "best_model.joblib")
    with open("best_model.pkl", "wb") as f:
        pickle.dump(best_model, f)
    with open("best_model_name.txt", "w") as f:
        f.write(best_name)
    print("Saved scikit-learn model to best_model.joblib and best_model.pkl")

print("Saved tfidf_vectorizer.joblib and label_encoder.joblib")

