# -*- coding: utf-8 -*-
"""Copy_of_Copy_of_Untitled16 (1) (2).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZrjiT70ta8d_2mRO7-b32P09Ubp8dDA8

# Installation - Langextract
"""

!pip install langextract

"""# Initialization"""

import textwrap
import langextract as lx
import os
import json


# 1) Your prompt (unchanged)
prompt = textwrap.dedent("""\
You are an expert at analyzing smartphone reviews. Your task is to extract specific features (sub_aspects), user opinions, and objective details, and to categorize each sub_aspect.

**Primary Aspect Categories (for classification):**
- **Battery**: Includes battery life, screen-on time, standby time, charging speed, wireless charging, reverse wireless charging (power sharing), battery health/degradation, overheating during charging.
- **Camera**: Includes photo quality (general), image sharpness/detail, color accuracy, dynamic range, low-light/night mode performance, portrait mode/bokeh, video quality, video stabilization, zoom performance (optical/digital), selfie/front camera quality, camera app interface, processing speed.
- **Display**: Includes brightness (indoor/outdoor), resolution/sharpness, color accuracy/vibrancy, refresh rate (smoothness), size, screen-to-body ratio/bezels, touch responsiveness, Always-On Display, notch/cutout design, screen durability/scratch resistance.
- **Performance**: Includes processing speed (general), app launch speed, multitasking/RAM management, gaming performance, lag/stutter, smoothness/fluidity of UI, thermal performance/overheating.
- **Sound/Speaker**: Includes speaker quality (clarity, loudness), speaker volume, bass performance, stereo speaker separation, microphone quality, call quality, headphone jack (presence/absence), audio recording quality.
- **Design & Build**: Includes look/appearance, color/finish, style, camera module design, feel in hand, size, weight, button placement, grip/slipperiness, materials (plastic, glass, aluminum), durability/sturdiness, build precision (gaps, seams), water/dust resistance (IP rating).
- **Connectivity**: Includes network reception (4G/5G), call reception/dropped calls, Wi-Fi stability/speed, Bluetooth pairing/range, GPS accuracy.
- **Price & Value**: Includes price/cost, value for money, deals/discounts, resale value, cost of repairs..
- **Software & User Experience (UX)**: Includes operating system (OS), user interface (UI), ease of use, bugs/glitches, software updates (timeliness, frequency), bloatware/pre-installed apps, customization options, software features.
- **Features & Functionality**: Includes fingerprint sensor (speed, accuracy), face unlock (speed, reliability), internal storage capacity, expandable storage (SD card slot),  haptics/vibration motor, stylus/pen support, NFC functionality, special modes (e.g., gaming mode, one-handed mode).
- **Customer Support & Warranty**: Includes warranty coverage, customer service quality, repair process (speed, cost), ease of getting support.
- **Ecosystem & Accessories**: Includes in-box contents (charger, case, headphones), availability of third-party accessories, compatibility with other devices (e.g., smartwatches, laptops).

**Extraction Rules:**
You will create extractions with the type aspect_opinion. Each extraction must contain the following components:
1. Reviewer ID : givven in the text
2. span: The span is the most complete phrase from the text that logically connects the aspect and the opinion.
   Example: For "The camera takes amazing photos", the span would be "camera takes amazing photos".
3. attributes: A dictionary containing four key-value pairs that describe the span:
   primary_aspect: The high-level category for the feature being discussed.
   sub_aspect: The specific feature mentioned in the text (e.g., 'photo quality', 'battery life'). This can be an exact phrase or a normalized concept.
   opinion: The user's subjective feeling or description (e.g., 'takes amazing photos', 'lasts all day', 'is a major downside').
   sentiment: The classification of the opinion ('positive', 'negative', or 'neutral').
   Score: Analyse the opinion and give the score( -1 to +1 )

**CRITICAL INSTRUCTIONS**:
1. Group into One Extraction: Combine a related aspect and its opinion into a single aspect_opinion extraction. Do NOT create separate extractions for the aspect and the opinion.
2. Exact Text: The values for the opinion and the original sub_aspect phrase should be exact substrings from the review text.
3. Complete Attributes: Every aspect_opinion extraction MUST have all four attributes populated: primary_aspect, sub_aspect, opinion, and sentiment.
4. Categorization: The primary_aspect value MUST be one of the predefined Primary Aspect Categories listed above.
""")

# 2) Your examples (unchanged)
examples = [
    lx.data.ExampleData(
        text="reviewer id '12342' said : The camera takes amazing photos and the battery lasts all day.",
        extractions=[
            lx.data.Extraction(extraction_class="aspect_opinion",
                               extraction_text="camera takes amazing photos",
                               attributes={"user_id" : "12342" , "primary_aspect": "Camera", "sub_aspect": "photo quality",
                                           "opinion": "takes amazing photos", "sentiment": "positive", "score": 0.9}),
            lx.data.Extraction(extraction_class="aspect_opinion",
                               extraction_text="battery lasts all day",
                               attributes={"user_id" : "12342" , "primary_aspect": "Battery", "sub_aspect": "battery life",
                                           "opinion": "lasts all day", "sentiment": "positive", "score": 0.8}),
        ]
    ),
    lx.data.ExampleData(
        text="reviewer id '65545' said :Love the display brightness, but the high price is a major downside.",
        extractions=[
            lx.data.Extraction(extraction_class="aspect_opinion",
                               extraction_text="Love the display brightness",
                               attributes={"user_id" : "65545" ,"primary_aspect": "Display", "sub_aspect": "display brightness",
                                           "opinion": "Love", "sentiment": "positive", "score": 0.9}),
            lx.data.Extraction(extraction_class="aspect_opinion",
                               extraction_text="high price is a major downside",
                               attributes={"user_id" : "65545" ,"primary_aspect": "Price & Value", "sub_aspect": "price",
                                           "opinion": "is a major downside", "sentiment": "negative", "score": -0.8}),
        ]
    ),
    lx.data.ExampleData(
        text="reviewer id '7765' said : Great value for money. The build quality feels premium and fast charging is a nice bonus.",
        extractions=[
            lx.data.Extraction(extraction_class="aspect_opinion",
                               extraction_text="Great value for money",
                               attributes={"user_id" : "7765" ,"primary_aspect": "Price & Value", "sub_aspect": "value for money",
                                           "opinion": "Great", "sentiment": "positive", "score": 0.8}),
            lx.data.Extraction(extraction_class="aspect_opinion",
                               extraction_text="build quality feels premium",
                               attributes={"user_id" : "7765" ,"primary_aspect": "Design & Build", "sub_aspect": "build quality",
                                           "opinion": "feels premium", "sentiment": "positive", "score": 0.7}),
            lx.data.Extraction(extraction_class="aspect_opinion",
                               extraction_text="fast charging is a nice bonus",
                               attributes={"user_id" : "7765" ,"primary_aspect": "Battery", "sub_aspect": "charging speed",
                                           "opinion": "is a nice bonus", "sentiment": "positive", "score": 0.6}),
        ]
    )
]

"""# Generate the Review String, from json"""

import json
import re
from typing import List, Dict, Any, Optional

class JSONLoader:
    """
    A class to robustly load JSON data from a file, handling various formats
    like standard JSON, JSON Lines (JSONL), and pretty-printed JSON.
    """
    def __init__(self, path: str):
        self.path = path

    def _read_content(self) -> str:
        """Reads the content of the file and strips the BOM character."""
        with open(self.path, "r", encoding="utf-8") as f:
            content = f.read()
        return content.lstrip("\ufeff").strip()

    def _parse_as_array(self, content: str) -> Optional[List[Dict]]:
        """Tries to parse the content as a single JSON array."""
        if "[" in content and "]" in content:
            first = content.find("[")
            last = content.rfind("]")
            arr_text = content[first:last + 1]
            arr_text = re.sub(r",\s*(\])", r"\1", arr_text)
            try:
                data = json.loads(arr_text)
                if isinstance(data, list):
                    return data
            except (json.JSONDecodeError, Exception):
                pass
        return None

    def _parse_as_jsonl(self, content: str) -> Optional[List[Dict]]:
        """Tries to parse the content as JSON Lines (one object per line)."""
        items = []
        for line in content.splitlines():
            line = line.strip()
            if not line:
                continue
            try:
                items.append(json.loads(line))
            except json.JSONDecodeError:
                return None  # Return None immediately if any line fails to parse strictly
        return items

    def _parse_with_brace_counting(self, content: str) -> List[Dict]:
        """Assembles pretty-printed JSON objects by counting braces."""
        items = []
        buffer = []
        depth = 0
        for line in content.splitlines():
            line = line.strip()
            if not line:
                continue
            depth += line.count("{") - line.count("}")
            buffer.append(line)
            if depth == 0 and buffer:
                chunk = "\n".join(buffer).strip().rstrip(",")
                try:
                    obj = json.loads(chunk)
                    items.append(obj)
                except json.JSONDecodeError:
                    pass
                buffer = []
        return items

    def load(self) -> List[Dict]:
        """
        The main public method to load data, trying different parsing strategies
        in order of strictness.
        """
        content = self._read_content()

        # 1. Try parsing as a standard JSON array
        items = self._parse_as_array(content)
        if items is not None:
            return items

        # 2. Fallback to strict JSONL
        items = self._parse_as_jsonl(content)
        if items is not None:
            return items

        # 3. Last resort: brace counting for pretty-printed objects
        return self._parse_with_brace_counting(content)

class ReviewProcessor:
    """A class to process a list of review objects and format them."""
    def __init__(self, items: List[Dict]):
        self.items = items

    def _extract_review_data(self, obj: Dict) -> Optional[tuple[Any, str]]:
        """Extracts the review ID and text from a single object."""
        rid = obj.get("Review_ID")
        if rid is None:
            rid = obj.get("review_id")

        text = (obj.get("review_text") or "").strip()

        if rid is not None and text:
            return rid, text
        return None

    def format_reviews(self) -> str:
        """
        Formats the list of review objects into a single string.
        """
        parts = []
        for obj in self.items:
            data = self._extract_review_data(obj)
            if data:
                rid, text = data
                parts.append(f"reviewer '{rid}' said : {text}")

        return "\n".join(parts) + "\n"

# --- Main Execution ---
if __name__ == "__main__":
    file_path = "combined_reviews.json"

    # Load the items using the structured class
    try:
        loader = JSONLoader(file_path)
        items = loader.load()
    except FileNotFoundError:
        print(f"Error: The file at '{file_path}' was not found.")
        items = []

    # Process and format the reviews
    processor = ReviewProcessor(items)
    reviews_text = processor.format_reviews()

    # Quick sanity check
    print(f"Loaded {len(items)} items, produced {reviews_text.count('reviewer')} review lines.")
    print(reviews_text)

"""# Run the model"""

result = lx.extract(
    text_or_documents=reviews_text,
    prompt_description=prompt,
    examples=examples,
    model_id="gemini-2.5-flash",
    api_key="AIzaSyACfcNVOjgIubO1qisMlYautiounWsLvyE"
)

"""# Store the results"""

lx.io.save_annotated_documents([result], output_name="extraction_results.jsonl", output_dir=".")